---
- name: Deploy ARM Template
  hosts: localhost
  collections:
  - azure.azcollection
  
  vars:
    RESOURCE_GROUP: z-mod-stack-rg
    KEY_VAULT: z-mod-stack-kv
    TENANT_ID: e6acf035-b480-4776-b7d2-d0aad2fcedb7
    USER_OBJECT_ID: 0c737172-e9c1-4bc2-970a-dc1f8ac041fa
    APP_OBJECT_ID: 339ff295-465e-495b-8df1-6ba39ff8c335
    RESOURCE_GROUP_DEV: z-mod-stack-dev-rg
    DEPLOYMENT_NAME: OCP-Cluster-Dev
    ARM_TEMPLATE: "{{ lookup('file', '../marketplace/mainTemplate.json') }}"
    ARM_PARAMETERS: "{{ (lookup('file', '../marketplace/mainParameters.json') | from_json).parameters }}"
    
  tasks:
  - name: Create Resource Group
    azure.azcollection.azure_rm_resourcegroup:
      name: "{{ RESOURCE_GROUP }}"
      location: "{{ LOCATION }}"

  - name: Create Key Vault
    azure_rm_keyvault:
      resource_group: "{{ RESOURCE_GROUP }}"
      vault_name: "{{ KEY_VAULT }}"
      enabled_for_template_deployment: yes
      vault_tenant: "{{ TENANT_ID }}"
      sku:
        name: standard
        family: A
      access_policies:
        - tenant_id: "{{ TENANT_ID }}"
          object_id: "{{ USER_OBJECT_ID }}"
          secrets:
            - get
            - list
            - set
            - delete
            - recover
            - backup
            - restore
            - purge
        - tenant_id: "{{ TENANT_ID }}"
          object_id: "{{ APP_OBJECT_ID }}"
          secrets:
            - get 

  - name: Create a Resource Group for OCP Deployment
    azure.azcollection.azure_rm_resourcegroup:
      name: "{{ RESOURCE_GROUP_DEV }}"
      location: "{{ LOCATION }}"

  - name: Create OCP Cluster
    azure.azcollection.azure_rm_deployment:
      name: "{{ DEPLOYMENT_NAME }}"
      resource_group_name: "{{ RESOURCE_GROUP_DEV }}"
      location: "{{ LOCATION }}"
      template: "{{ ARM_TEMPLATE }}"
      parameters: "{{ ARM_PARAMETERS }}"