name: Azure Deployment

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/azure-deploy-ansible.yml'
      - 'azure/**' 

env:
  ARM_TTK_PATH: azure/marketplace/
  ANSIBLE_PLAYBOOK: azure/ansible/run-provision.yml 

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run ARM-TTK
      uses: venura9/arm-ttk@master
      with: 
        path: ${{ env.ARM_TTK_PATH }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9    
    - name: Install dependencies Including Ansible
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi 
    - name: 'AZ CLI login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  
    - name: Ansible Playbook Runner
      uses: euclid1990/actions-ansible@v2
      with:
        playbook: ${{ env.ANSIBLE_PLAYBOOK }}
