name: Run Azure Login 1

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/azure1.yml'
      - 'azure1/**'

env:
  RESOURCE_GROUP_NAME: z-mod-stack-dev-rg
  RESOURCE_GROUP_LOCATION: eastus
  ARM_TEMPLATE: azure1/marketplace/mainTemplate.json
  ARM_PARAMETERS: azure2/marketplace/mainParameters.json

jobs: 
  build-and-deploy-1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2    
    - name: 'AZ CLI login 1'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.RESOURCE_GROUP_LOCATION }}
          echo "Azure resource group created"    
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        template: ${{ env.ARM_TEMPLATE }}
        parameters: ${{ env.ARM_PARAMETERS }}