name: Run Azure Login 1

on:
  push:
    branches:
      - dev
    paths:
      - 'azure1/**'

#permissions:
#      id-token: write
#      contents: read

jobs: 
  build-and-deploy-1:
    runs-on: ubuntu-latest
    steps:
    - name: 'AZ CLI login 1'
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
#         client-id: ${{ vars.AZURE_CLIENT_ID }}
#         tenant-id: ${{ vars.AZURE_TENANT_ID }}
#         subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands 1'
      run: |
          az account show
          az group list
          pwd