name: Infra Provision

on:
  push:
    branches:
      - dev
    paths:
      - 'azure/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'azure/**'  
  workflow_dispatch:
  
env:
  RG_NAME: z-mod-stack-rg
  KV_NAME: zmodstackkv
  
jobs:
  build:
    name: Infra
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: AZ CLI Login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run Azure CLI commands'
        run: |
          az account show
          az group list
          pwd