name: Run Azure Login with OpenID Connect
on: [push]

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          creds: ${{ vars.AZURE_CLIENT_SECRET }}
#         tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd